name: Atualizar EPG Lourival26

on:
  schedule:
    - cron: '0 3 * * *' # Roda todo dia às 03:00 da manhã
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Garante permissão para enviar os arquivos atualizados
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar o script Lourival26
        run: python main.py

      - name: Enviar alterações para o GitHub
        run: |
          git config --global user.name "Lourival26-Bot"
          git config --global user.email "bot@lourival26.com"
          git add epg-brasil.xml
          # Só faz o commit se houver alterações no EPG
          git diff --quiet && git diff --staged --quiet || git commit -m "Automação: EPG atualizado pelo robô Lourival26"
          git push
          
